<?php

namespace ContainerVY2QCJY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfoClientDemoTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\InfoClientDemoType' shared autowired service.
     *
     * @return \App\Form\InfoClientDemoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/InfoClientDemoType.php';

        return $container->privates['App\\Form\\InfoClientDemoType'] = new \App\Form\InfoClientDemoType();
    }
}
