<?php

namespace ContainerL99j3vv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MXUpD2_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.mXUpD2.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mXUpD2.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'file' => ['privates', '.errored..service_locator.mXUpD2..App\\Entity\\FichierClient', NULL, 'Cannot autowire service ".service_locator.mXUpD2.": it references class "App\\Entity\\FichierClient" but no such service exists.'],
        ], [
            'file' => 'App\\Entity\\FichierClient',
        ]);
    }
}
