<?php

namespace ContainerL99j3vv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFdControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FdController' shared autowired service.
     *
     * @return \App\Controller\FdController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FdController'] = $instance = new \App\Controller\FdController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\FdController', $container));

        return $instance;
    }
}
