<?php

namespace ContainerL99j3vv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormLoginAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\FormLoginAuthenticator' shared autowired service.
     *
     * @return \App\Security\FormLoginAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\FormLoginAuthenticator'] = new \App\Security\FormLoginAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
