<?php

namespace ContainerL99j3vv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFichierClientService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.mXUpD2..App\Entity\FichierClient' shared service.
     *
     * @return \App\Entity\FichierClient
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mXUpD2.": it references class "App\\Entity\\FichierClient" but no such service exists.');
    }
}
