<?php

namespace ContainerKkjjW0j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFichierDemandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.15TUzD3.App\Entity\FichierDemande' shared service.
     *
     * @return \App\Entity\FichierDemande
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.15TUzD3": it references class "App\\Entity\\FichierDemande" but no such service exists.');
    }
}
