<?php

namespace ContainerCGx1nNK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_15TUzD3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.15TUzD3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.15TUzD3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fd' => ['privates', '.errored..service_locator.15TUzD3.App\\Entity\\FichierDemande', NULL, 'Cannot autowire service ".service_locator.15TUzD3": it references class "App\\Entity\\FichierDemande" but no such service exists.'],
        ], [
            'fd' => 'App\\Entity\\FichierDemande',
        ]);
    }
}
