<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL99j3vv\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL99j3vv/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL99j3vv.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL99j3vv\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerL99j3vv\App_KernelProdContainer([
    'container.build_hash' => 'L99j3vv',
    'container.build_id' => 'f8eaa1fe',
    'container.build_time' => 1654559327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL99j3vv');
