<?php

namespace Container5hfuUaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddFileTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\AddFileType' shared autowired service.
     *
     * @return \App\Form\AddFileType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddFileType.php';

        return $container->privates['App\\Form\\AddFileType'] = new \App\Form\AddFileType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
