<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVY2QCJY\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVY2QCJY/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVY2QCJY.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVY2QCJY\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerVY2QCJY\App_KernelTestDebugContainer([
    'container.build_hash' => 'VY2QCJY',
    'container.build_id' => '4ea8a00c',
    'container.build_time' => 1679860048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVY2QCJY');
