<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR9dFZAb\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR9dFZAb/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerR9dFZAb.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerR9dFZAb\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerR9dFZAb\App_KernelTestDebugContainer([
    'container.build_hash' => 'R9dFZAb',
    'container.build_id' => '3092f037',
    'container.build_time' => 1679851772,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR9dFZAb');
