<?php

namespace ContainerMaOsKcJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_85KzkXLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.85KzkXL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.85KzkXL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClientController::add_fd' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.8KVDEnY', 'get_ServiceLocator_8KVDEnYService', true],
            'App\\Controller\\ClientController::view_files_all' => ['privates', '.service_locator.L0jRHku', 'get_ServiceLocator_L0jRHkuService', true],
            'App\\Controller\\FdController::Dell_fd' => ['privates', '.service_locator.73RZARn', 'get_ServiceLocator_73RZARnService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController::View_clientall' => ['privates', '.service_locator._0ru0pR', 'get_ServiceLocator_0ru0pRService', true],
            'App\\Controller\\SecurityController::add_file' => ['privates', '.service_locator.dIKoJK_', 'get_ServiceLocator_DIKoJKService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController::suppfile' => ['privates', '.service_locator.u0e.oFD', 'get_ServiceLocator_U0e_OFDService', true],
            'App\\Controller\\SecurityController::view_files_all' => ['privates', '.service_locator.L0jRHku', 'get_ServiceLocator_L0jRHkuService', true],
            'App\\Controller\\SecurityController::view_files_filtre' => ['privates', '.service_locator.L0jRHku', 'get_ServiceLocator_L0jRHkuService', true],
            'App\\Controller\\SmsController::index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\SmsController::view' => ['privates', '.service_locator.8_0Zq_c', 'get_ServiceLocator_80ZqCService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ClientController:add_fd' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.8KVDEnY', 'get_ServiceLocator_8KVDEnYService', true],
            'App\\Controller\\ClientController:view_files_all' => ['privates', '.service_locator.L0jRHku', 'get_ServiceLocator_L0jRHkuService', true],
            'App\\Controller\\FdController:Dell_fd' => ['privates', '.service_locator.73RZARn', 'get_ServiceLocator_73RZARnService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController:View_clientall' => ['privates', '.service_locator._0ru0pR', 'get_ServiceLocator_0ru0pRService', true],
            'App\\Controller\\SecurityController:add_file' => ['privates', '.service_locator.dIKoJK_', 'get_ServiceLocator_DIKoJKService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController:suppfile' => ['privates', '.service_locator.u0e.oFD', 'get_ServiceLocator_U0e_OFDService', true],
            'App\\Controller\\SecurityController:view_files_all' => ['privates', '.service_locator.L0jRHku', 'get_ServiceLocator_L0jRHkuService', true],
            'App\\Controller\\SecurityController:view_files_filtre' => ['privates', '.service_locator.L0jRHku', 'get_ServiceLocator_L0jRHkuService', true],
            'App\\Controller\\SmsController:index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\SmsController:view' => ['privates', '.service_locator.8_0Zq_c', 'get_ServiceLocator_80ZqCService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ClientController::add_fd' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::view_files_all' => '?',
            'App\\Controller\\FdController::Dell_fd' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::View_clientall' => '?',
            'App\\Controller\\SecurityController::add_file' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::suppfile' => '?',
            'App\\Controller\\SecurityController::view_files_all' => '?',
            'App\\Controller\\SecurityController::view_files_filtre' => '?',
            'App\\Controller\\SmsController::index' => '?',
            'App\\Controller\\SmsController::view' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ClientController:add_fd' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:view_files_all' => '?',
            'App\\Controller\\FdController:Dell_fd' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:View_clientall' => '?',
            'App\\Controller\\SecurityController:add_file' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:suppfile' => '?',
            'App\\Controller\\SecurityController:view_files_all' => '?',
            'App\\Controller\\SecurityController:view_files_filtre' => '?',
            'App\\Controller\\SmsController:index' => '?',
            'App\\Controller\\SmsController:view' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
