<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMaOsKcJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMaOsKcJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMaOsKcJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMaOsKcJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMaOsKcJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'MaOsKcJ',
    'container.build_id' => '55bd4655',
    'container.build_time' => 1654671786,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMaOsKcJ');
