<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQcYJYO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQcYJYO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRQcYJYO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRQcYJYO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRQcYJYO\App_KernelDevDebugContainer([
    'container.build_hash' => 'RQcYJYO',
    'container.build_id' => '1eabecfb',
    'container.build_time' => 1679407192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRQcYJYO');
