<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUUxWXtO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUUxWXtO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUUxWXtO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUUxWXtO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUUxWXtO\App_KernelDevDebugContainer([
    'container.build_hash' => 'UUxWXtO',
    'container.build_id' => 'a4bc42dc',
    'container.build_time' => 1679859876,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUUxWXtO');
