<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InfoClient extends \App\Entity\InfoClient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Mail', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'nom_Societe', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Num_pro', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Cp', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Ville', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'num_siret', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'id_adm'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Mail', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'nom_Societe', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Num_pro', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Cp', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'Ville', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'num_siret', '' . "\0" . 'App\\Entity\\InfoClient' . "\0" . 'id_adm'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InfoClient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $Nom): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$Nom]);

        return parent::setNom($Nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $Prenom): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$Prenom]);

        return parent::setPrenom($Prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail(string $Mail): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$Mail]);

        return parent::setMail($Mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSociete(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSociete', []);

        return parent::getNomSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSociete(string $nom_Societe): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSociete', [$nom_Societe]);

        return parent::setNomSociete($nom_Societe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $Adresse): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$Adresse]);

        return parent::setAdresse($Adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumPro(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumPro', []);

        return parent::getNumPro();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumPro(int $Num_pro): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumPro', [$Num_pro]);

        return parent::setNumPro($Num_pro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp(int $Cp): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$Cp]);

        return parent::setCp($Cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $Ville): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$Ville]);

        return parent::setVille($Ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSiret(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSiret', []);

        return parent::getNumSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSiret(string $num_siret): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSiret', [$num_siret]);

        return parent::setNumSiret($num_siret);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAdm(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAdm', []);

        return parent::getIdAdm();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAdm(int $id_adm): \App\Entity\InfoClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAdm', [$id_adm]);

        return parent::setIdAdm($id_adm);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
